name: faster
description: The best runner ever.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.0.0
  flame_audio: ^1.0.0
  flame_oxygen: ^0.1.1
  easy_localization: ^3.0.0
  json_annotation: ^4.4.0
  json_serializable: ^6.1.4
  provider: ^6.0.2
  shared_preferences: ^2.0.13

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_native_splash: ^2.0.1+1

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/i18n/
    - assets/images/
    - assets/config/

  fonts:
    - family: RoadRage
      fonts:
        - asset: assets/fonts/RoadRage-Regular.ttf